# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('vod_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.VideoCategory', verbose_name='\uce74\ud14c\uace0\ub9ac')),
            ],
        ),
    ]
